name: geojson
description: Utilities to work with geojson data. Parser with a reactive api,
  search and geofencing
homepage: https://github.com/synw/geojson
version: 0.10.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  geodesy: ^0.4.0-nullsafety.0
  geopoint: ^0.9.0
  iso: ^1.0.0

dependency_overrides:
  geopoint:
    git:
      url: https://github.com/it-sam/geopoint.git
      commit: 7a28e2

dev_dependencies:
  extra_pedantic: ^1.4.0
  test: ^1.17.4
